Pantry Inventory: com.example.pantryinventory.RecyclerViewAdapter Class Reference
com.example.pantryinventory.RecyclerViewAdapter Class Reference
Classes
interface OnItemListener
class ViewHolder
Public Member Functions
RecyclerViewAdapter (List< ItemData > itemDataList, boolean isNotification, OnItemListener onItemListener)
ViewHolder onCreateViewHolder (@NonNull ViewGroup parent, int viewType)
void onBindViewHolder (@NonNull ViewHolder holder, int position)
int getItemCount ()
Constructor & Destructor Documentation
RecyclerViewAdapter()
com.example.pantryinventory.RecyclerViewAdapter.RecyclerViewAdapter (List< ItemData > itemDataList, boolean isNotification, OnItemListener onItemListener)
Member Function Documentation
getItemCount()
int com.example.pantryinventory.RecyclerViewAdapter.getItemCount ()
onBindViewHolder()
void com.example.pantryinventory.RecyclerViewAdapter.onBindViewHolder (@NonNull ViewHolder holder, int position)
References com.example.pantryinventory.ItemData.getExpDate(), com.example.pantryinventory.ItemData.getFoodName(), and com.example.pantryinventory.ItemData.getImageUrl().
onCreateViewHolder()
ViewHolder com.example.pantryinventory.RecyclerViewAdapter.onCreateViewHolder (@NonNull ViewGroup parent, int viewType)
The documentation for this class was generated from the following file:
app/src/main/java/com/example/pantryinventory/RecyclerViewAdapter.java