Pantry Inventory: com.example.pantryinventory.LoginManager Class Reference
com.example.pantryinventory.LoginManager Class Reference
Classes
interface LoginCallback
Public Member Functions
LoginManager (FirebaseAuth firebaseAuth)
void signIn (String email, String password, final LoginCallback callback)
FirebaseUser getCurrentUser ()
Constructor & Destructor Documentation
LoginManager()
com.example.pantryinventory.LoginManager.LoginManager (FirebaseAuth firebaseAuth)
Member Function Documentation
getCurrentUser()
FirebaseUser com.example.pantryinventory.LoginManager.getCurrentUser ()
Referenced by com.example.pantryinventory.Login.onStart().
signIn()
void com.example.pantryinventory.LoginManager.signIn (String email, String password, final LoginCallback callback)
References com.example.pantryinventory.LoginManager.LoginCallback.onFailure(), and com.example.pantryinventory.LoginManager.LoginCallback.onSuccess().
Referenced by com.example.pantryinventory.LoginTest.signIn_withInvalidCredentials_callsOnFailure(), and com.example.pantryinventory.LoginTest.signIn_withValidCredentials_callsOnSuccess().
The documentation for this class was generated from the following file:
app/src/main/java/com/example/pantryinventory/LoginManager.java