Pantry Inventory: com.example.pantryinventory.ItemData Class Reference
com.example.pantryinventory.ItemData Class Reference
Public Member Functions
ItemData ()
ItemData (String imageUrl, String foodName, String expDate)
String getImageUrl ()
void setImageUrl (String imageUrl)
String getFoodName ()
void setFoodName (String foodName)
String getExpDate ()
void setExpDate (String expDate)
Constructor & Destructor Documentation
ItemData() [1/2]
com.example.pantryinventory.ItemData.ItemData ()
ItemData() [2/2]
com.example.pantryinventory.ItemData.ItemData (String imageUrl, String foodName, String expDate)
Member Function Documentation
getExpDate()
String com.example.pantryinventory.ItemData.getExpDate ()
Referenced by com.example.pantryinventory.RecyclerViewAdapter.onBindViewHolder(), and com.example.pantryinventory.AddFoods.onCreate().
getFoodName()
String com.example.pantryinventory.ItemData.getFoodName ()
Referenced by com.example.pantryinventory.RecyclerViewAdapter.onBindViewHolder(), and com.example.pantryinventory.AddFoods.onCreate().
getImageUrl()
String com.example.pantryinventory.ItemData.getImageUrl ()
Referenced by com.example.pantryinventory.RecyclerViewAdapter.onBindViewHolder(), and com.example.pantryinventory.AddFoods.onCreate().
setExpDate()
void com.example.pantryinventory.ItemData.setExpDate (String expDate)
setFoodName()
void com.example.pantryinventory.ItemData.setFoodName (String foodName)
setImageUrl()
void com.example.pantryinventory.ItemData.setImageUrl (String imageUrl)
The documentation for this class was generated from the following file:
app/src/main/java/com/example/pantryinventory/ItemData.java