Pantry Inventory: com.example.pantryinventory.FirebaseDBHelper Class Reference
com.example.pantryinventory.FirebaseDBHelper Class Reference
Classes
interface DataStatus
Public Member Functions
FirebaseDBHelper ()
void readItems (final DataStatus dataStatus)
void deleteItem (String key, final DataStatus dataStatus)
Constructor & Destructor Documentation
FirebaseDBHelper()
com.example.pantryinventory.FirebaseDBHelper.FirebaseDBHelper ()
Member Function Documentation
deleteItem()
void com.example.pantryinventory.FirebaseDBHelper.deleteItem (String key, final DataStatus dataStatus)
References com.example.pantryinventory.FirebaseDBHelper.DataStatus.DataIsDeleted().
Referenced by com.example.pantryinventory.MainActivity.onDeleteClick(), and com.example.pantryinventory.NotificationList.onDeleteClick().
readItems()
void com.example.pantryinventory.FirebaseDBHelper.readItems (final DataStatus dataStatus)
References com.example.pantryinventory.FirebaseDBHelper.DataStatus.DataIsLoaded().
The documentation for this class was generated from the following file:
app/src/main/java/com/example/pantryinventory/FirebaseDBHelper.java